CREATE TABLE `TB_AF_COMPLETE` (
  `COMPLETE_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '완료작업ID',
  `RUN_ID` varchar(100) NOT NULL COMMENT '실행인스턴스ID',
  `CONTENT` longtext NOT NULL COMMENT '작업내용',
  `USE_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  `RGDT` datetime NOT NULL DEFAULT current_timestamp() COMMENT '시작일시',
  `UPDT` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '수정일시',
  PRIMARY KEY (`COMPLETE_ID`),
  CONSTRAINT `CHK_JSON_CONTENT` CHECK (json_valid(`CONTENT`))
) ENGINE=InnoDB AUTO_INCREMENT=68 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='완료작업 정보';

CREATE TABLE `TB_AF_COMPLETE_MAP` (
  `COMPLETE_ID` int(11) DEFAULT NULL COMMENT '완료작업ID',
  `TABLE_ID` int(11) DEFAULT NULL COMMENT '테이블ID',
  `PK_VALUE` int(11) DEFAULT NULL COMMENT '테이블 PK값',
  KEY `IDX_TABLE_PK` (`TABLE_ID`,`PK_VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='완료작업 매핑';


CREATE TABLE `TB_AF_DAG` (
  `DAG_ID` varchar(250) NOT NULL COMMENT 'DAG ID',
  `DAG_DESC` varchar(200) NOT NULL COMMENT 'DAG 설명',
  `DAG_FILE_PATH` varchar(500) NOT NULL COMMENT 'DAG 파일경로',
  `USE_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  `RGDT` datetime NOT NULL DEFAULT current_timestamp() COMMENT '시작일시',
  `UPDT` datetime NOT NULL DEFAULT current_timestamp() COMMENT '수정일시',
  PRIMARY KEY (`DAG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `TB_AF_RUN` (
  `RUN_ID` varchar(100) NOT NULL COMMENT 'RUN ID',
  `DAG_ID` varchar(250) NOT NULL COMMENT 'DAG ID',
  `START_DATE` datetime DEFAULT NULL,
  `END_DATE` datetime DEFAULT NULL,
  `STATUS` char(1) NOT NULL DEFAULT 'W' COMMENT '사용여부',
  `RGDT` datetime NOT NULL DEFAULT current_timestamp() COMMENT '시작일시',
  `UPDT` datetime NOT NULL DEFAULT current_timestamp() COMMENT '수정일시',
  PRIMARY KEY (`RUN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `TB_AF_TARGET` (
  `RUN_ID` varchar(100) NOT NULL COMMENT 'RUN ID',
  `TARGET_ID` varchar(36) NOT NULL COMMENT 'TARGET ID',
  `CONTENT` longtext NOT NULL COMMENT 'TARGET JSON',
  `USE_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  `RGDT` datetime NOT NULL DEFAULT current_timestamp() COMMENT '시작일시',
  `UPDT` datetime NOT NULL DEFAULT current_timestamp() COMMENT '수정일시',
  PRIMARY KEY (`RUN_ID`,`TARGET_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `TB_CO_CODE` (
  `CD` varchar(50) NOT NULL COMMENT '코드',
  `CD_GRP` varchar(50) NOT NULL COMMENT '코드그룹',
  `CD_NM` varchar(100) NOT NULL COMMENT '코드명',
  `CD_VAL` varchar(100) DEFAULT NULL COMMENT '코드값',
  `CD_DESC` varchar(200) DEFAULT NULL COMMENT '코드설명',
  `CD_ORDR` int(11) DEFAULT 0 COMMENT '코드순서',
  `CD_PROP1` varchar(100) DEFAULT NULL COMMENT '코드속성1',
  `CD_PROP2` varchar(100) DEFAULT NULL COMMENT '코드속성2',
  `CD_PROP3` varchar(100) DEFAULT NULL COMMENT '코드속성3',
  `USE_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  `RGDT` datetime NOT NULL DEFAULT current_timestamp() COMMENT '시작일시',
  `UPDT` datetime NOT NULL DEFAULT current_timestamp() COMMENT '수정일시',
  PRIMARY KEY (`CD`,`CD_GRP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `TB_CO_CODEGROUP` (
  `CD_GRP` varchar(50) NOT NULL COMMENT '코드그룹',
  `CD_GRP_NM` varchar(100) NOT NULL COMMENT '코드그룹명',
  `CD_GRP_DESC` varchar(200) DEFAULT NULL COMMENT '코드그룹설명',
  `USE_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  `RGDT` datetime NOT NULL DEFAULT current_timestamp() COMMENT '등록일시',
  `UPDT` datetime NOT NULL DEFAULT current_timestamp() COMMENT '수정일시',
  PRIMARY KEY (`CD_GRP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `TB_DI_BLOCK_CLASS` (
  `BLOCK_CLASS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SECTION_CLASS_ID` int(11) NOT NULL COMMENT '영역 클래스 ID',
  `BLOCK_ROW_NUM` int(11) DEFAULT 0 COMMENT '블록 행 값',
  `BLOCK_COL_NUM` int(11) DEFAULT 0 COMMENT '블록 열 값',
  `BLOCK_TYPE` varchar(50) DEFAULT NULL COMMENT '블록 구분',
  `COLUMN_ID` int(11) DEFAULT NULL COMMENT '컬럼 ID',
  `DEFAULT_TEXT` varchar(200) DEFAULT NULL COMMENT '기본값 텍스트',
  PRIMARY KEY (`BLOCK_CLASS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `TB_DI_BLOCK_CRCTN` (
  `BLOCK_CRCTN_ID` int(11) NOT NULL AUTO_INCREMENT,
  `BLOCK_CLASS_ID` int(11) NOT NULL COMMENT '블록 클래스 ID',
  `ERROR_TEXT` varchar(50) DEFAULT NULL COMMENT '에러 텍스트',
  `CRRCT_TEXT` varchar(50) DEFAULT NULL COMMENT '교정 텍스트',
  `CRCTN_CNT` int(11) DEFAULT NULL COMMENT '교정 횟수',
  `CRCTN_ORDER` int(11) DEFAULT 0,
  PRIMARY KEY (`BLOCK_CRCTN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `TB_DI_COMMON_CRCTN` (
  `COMMON_CRCTN_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ERROR_TEXT` varchar(50) DEFAULT NULL COMMENT '에러 텍스트',
  `CRRCT_TEXT` varchar(50) DEFAULT NULL COMMENT '교정 텍스트',
  `CRCTN_CNT` int(11) DEFAULT NULL COMMENT '교정 횟수',
  PRIMARY KEY (`COMMON_CRCTN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `TB_DI_DOC_CLASS` (
  `DOC_CLASS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DOC_NAME` varchar(100) DEFAULT NULL COMMENT '문서 클래스 명',
  `RGDT` datetime DEFAULT current_timestamp(),
  `UPDT` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`DOC_CLASS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `TB_DI_LAYOUT_CLASS` (
  `LAYOUT_CLASS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DOC_CLASS_ID` int(11) NOT NULL COMMENT '문서 클래스 ID',
  `LAYOUT_NAME` varchar(100) DEFAULT NULL COMMENT '레이아웃 클래스명',
  `LAYOUT_DESC` varchar(200) DEFAULT NULL COMMENT ' ',
  `LAYOUT_ORDER` int(11) DEFAULT 0 COMMENT '레이아웃 순서',
  `IMG_PREPROCESS_INFO` longtext DEFAULT NULL COMMENT '이미지 전처리 정보',
  `CLASSIFY_AI_INFO` longtext DEFAULT NULL COMMENT '분류 ai 정보',
  `RGDT` datetime DEFAULT current_timestamp(),
  `UPDT` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`LAYOUT_CLASS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `TB_DI_SECTION_CLASS` (
  `SECTION_CLASS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LAYOUT_CLASS_ID` int(11) NOT NULL COMMENT '레이아웃 클래스 ID',
  `SECTION_NAME` varchar(100) DEFAULT NULL COMMENT '구역 명',
  `SECTION_DESC` varchar(200) DEFAULT NULL,
  `SEPARATE_AREA_INFO` longtext DEFAULT NULL COMMENT '영역분리 정보',
  `SEPARATE_BLOCK_INFO` longtext DEFAULT NULL COMMENT '영역블록 정보',
  `OCR_INFO` longtext DEFAULT NULL COMMENT 'OCR 정보',
  `CLEANSING_INFO` longtext DEFAULT NULL COMMENT '정제 정보',
  `RGDT` datetime DEFAULT current_timestamp(),
  `UPDT` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `SECTION_ORDER` int(11) DEFAULT 0,
  `STRUCTURING_INFO` longtext DEFAULT NULL COMMENT '구조화 정보',
  `SECTION_TYPE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`SECTION_CLASS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=40 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `TB_DS_COLUMN` (
  `COLUMN_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '컬럼ID',
  `TABLE_ID` int(11) NOT NULL COMMENT '테이블ID',
  `COLUMN_NAME` varchar(100) NOT NULL COMMENT '컬럼명',
  `DATA_TYPE` varchar(50) NOT NULL COMMENT '데이터 타입',
  `IS_NULLABLE` char(1) NOT NULL DEFAULT 'Y' COMMENT 'NULL 허용 여부',
  `IS_PK` char(1) NOT NULL DEFAULT 'N' COMMENT 'PK 여부',
  `COLUMN_DESC` varchar(200) DEFAULT NULL COMMENT '컬럼 설명',
  `COLUMN_ORDER` int(11) DEFAULT NULL COMMENT '컬럼 순서',
  `FORMAT_INFO` longtext DEFAULT NULL COMMENT '포맷정보',
  PRIMARY KEY (`COLUMN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=43 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='데이터 테이블 컬럼';

CREATE TABLE `TB_DS_TABLE` (
  `TABLE_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '테이블ID',
  `TABLE_NM` varchar(100) NOT NULL COMMENT '테이블명',
  `TABLE_DESC` varchar(200) DEFAULT NULL COMMENT '테이블 설명',
  `PARENT_TABLE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`TABLE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='데이터 테이블';

CREATE TABLE `TB_OCR_BILD_BASIC_INFO` (
  `BILD_SEQ_NUM` int(11) NOT NULL AUTO_INCREMENT COMMENT '건물 시퀀스 번호',
  `BILD_ID` varchar(50) DEFAULT NULL COMMENT '건축물 고유 식별자',
  `UNIQUE_NUM` varchar(50) DEFAULT NULL COMMENT '건축물 고유번호',
  `BILD_NM` varchar(100) DEFAULT NULL COMMENT '건축물 명칭',
  `UNIT_HOUSEHOLD_POP` varchar(50) DEFAULT NULL COMMENT '호수/가구수/세대수',
  `LAND_LOC_ADDR` varchar(255) DEFAULT NULL COMMENT '대지위치 주소',
  `LAND_LOT_NUM` varchar(50) DEFAULT NULL COMMENT '지번',
  `ROAD_NM_ADDR` varchar(255) DEFAULT NULL COMMENT '도로명주소',
  `LAND_AREA_SQM` varchar(100) DEFAULT NULL COMMENT '대지 면적 (제곱미터)',
  `TOT_FLR_AREA_SQM` varchar(100) DEFAULT NULL COMMENT '연면적 (제곱미터)',
  `ADMIN_DIST_NM` varchar(50) DEFAULT NULL COMMENT '지역명',
  `SECT_TYPE` varchar(50) DEFAULT NULL COMMENT '지구 유형',
  `ZONE_TYPE` varchar(50) DEFAULT NULL COMMENT '구역 유형',
  `BILD_AREA_SQM` varchar(100) DEFAULT NULL COMMENT '건축 면적 (제곱미터)',
  `FAR_CALC_AREA_SQM` varchar(100) DEFAULT NULL COMMENT '용적률 산정 연면적 (제곱미터)',
  `MAIN_STRUCT_TYPE` varchar(100) DEFAULT NULL COMMENT '주구조 유형',
  `MAIN_PURPOSE_TYPE` varchar(100) DEFAULT NULL COMMENT '주용도 유형',
  `TOT_FLR_CNT` varchar(50) DEFAULT NULL COMMENT '총 층수',
  `BILD_COVERAGE_RATIO` varchar(100) DEFAULT NULL COMMENT '건폐율 (%)',
  `FLR_AREA_RATIO` varchar(100) DEFAULT NULL COMMENT '용적률 (%)',
  `BILD_HEIGHT_METER` varchar(100) DEFAULT NULL COMMENT '건축물 높이 (미터)',
  `ROOF_STRUCT_TYPE` varchar(100) DEFAULT NULL COMMENT '지붕 구조 유형',
  `ANNEX_BILD_TYPE` varchar(50) DEFAULT NULL COMMENT '부속 건축물 유형',
  `LNDSCP_AREA_SQM` varchar(100) DEFAULT NULL COMMENT '조경 면적 (제곱미터)',
  `PUB_OPEN_AREA_SQM` varchar(100) DEFAULT NULL COMMENT '공개 공지 면적 (제곱미터)',
  `SETBACK_AREA_SQM` varchar(100) DEFAULT NULL COMMENT '건축선 후퇴 면적 (제곱미터)',
  `SETBACK_DIST_METER` varchar(100) DEFAULT NULL COMMENT '건축선 후퇴 거리 (미터)',
  PRIMARY KEY (`BILD_SEQ_NUM`)
) ENGINE=InnoDB AUTO_INCREMENT=189 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `TB_OCR_FLR_STATUS` (
  `FLR_SEQ_NUM` int(11) NOT NULL AUTO_INCREMENT COMMENT '건축물 현황 시쿼번호',
  `BILD_SEQ_NUM` varchar(255) NOT NULL COMMENT '건물 시퀀스 번호',
  `FLR_CLASS_TYPE` varchar(20) DEFAULT NULL COMMENT '층 구분 유형 (예: 주1, 지1)',
  `FLR_NUM_TEXT` varchar(20) DEFAULT NULL COMMENT '층 번호 (예: 1, 지하1층)',
  `FLR_STRUCT_TYPE` varchar(100) DEFAULT NULL COMMENT '층 구조 유형',
  `FLR_PURP_TYPE` varchar(100) DEFAULT NULL COMMENT '층 용도 유형',
  `FLR_AREA_SQM` varchar(100) DEFAULT NULL COMMENT '층 면적 (제곱미터)',
  PRIMARY KEY (`FLR_SEQ_NUM`)
) ENGINE=InnoDB AUTO_INCREMENT=753 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `TB_OCR_OWN_STATUS` (
  `OWNR_SEQ_NUM` int(11) NOT NULL AUTO_INCREMENT COMMENT '소유자 현황 시퀀스 번호',
  `BILD_SEQ_NUM` varchar(255) NOT NULL COMMENT '건물 시퀀스 번호',
  `OWNR_FULL_NM` varchar(100) DEFAULT NULL COMMENT '소유자 성명 또는 명칭',
  `OWNR_ID_REG_NUM` varchar(50) DEFAULT NULL COMMENT '주민/법인 등록번호',
  `OWNR_ADDR_FULL` varchar(255) DEFAULT NULL COMMENT '소유자 전체 주소',
  `OWNR_SHARE_RATIO` varchar(20) DEFAULT NULL COMMENT '소유권 지분 비율',
  `OWNR_CHG_DATE` varchar(100) DEFAULT NULL COMMENT '소유권 변동일',
  `ADDR_CHG_CATEGORY` varchar(100) DEFAULT NULL COMMENT '주소 변동 구분',
  PRIMARY KEY (`OWNR_SEQ_NUM`)
) ENGINE=InnoDB AUTO_INCREMENT=378 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `TB_OCR_TRN_LOG` (
  `LOG_SEQ_NUM` int(11) NOT NULL AUTO_INCREMENT COMMENT '로그 시퀀스 번호',
  `TRN_TABLE_NAME` varchar(255) NOT NULL,
  `TRN_TABLE_PK` varchar(255) DEFAULT NULL,
  `TRN_COL_ID` varchar(255) DEFAULT NULL,
  `ORI_TEXT` text DEFAULT NULL,
  `TRN_TEXT` text DEFAULT NULL,
  PRIMARY KEY (`LOG_SEQ_NUM`)
) ENGINE=InnoDB AUTO_INCREMENT=1355 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;