CREATE TABLE `TB_CO_CODEGROUP` (
	`CD_GRP`	varchar(50)	NOT NULL  PRIMARY KEY  COMMENT '코드그룹',
	`CD_GRP_NM`	varchar(100)	NOT NULL	COMMENT '코드그룹명',
	`CD_GRP_DESC`	varchar(200)	NULL	COMMENT '코드그룹설명',
	`USE_YN`	char(1)	NOT NULL	DEFAULT 'Y'	COMMENT '사용여부',
	`RGDT`	datetime	NOT NULL	DEFAULT current_timestamp()	COMMENT '등록일시',
	`UPDT`	datetime	NOT NULL	DEFAULT current_timestamp() on update current_timestamp()	COMMENT '수정일시'
) COMMENT '코드그룹';


CREATE TABLE `TB_CO_CODE` (
	`CD`	varchar(50)	NOT NULL  PRIMARY KEY  COMMENT '코드',
	`CD_GRP`	varchar(50)	NOT NULL  PRIMARY KEY  COMMENT '코드그룹',
	`CD_NM`	varchar(100)	NOT NULL	COMMENT '코드명',
	`CD_VAL`	VARCHAR(255)	NULL	COMMENT '코드값',
	`CD_DESC`	varchar(200)	NULL	COMMENT '코드설명',
	`CD_ORDR`	int	NULL	DEFAULT 0	COMMENT '코드순서',
	`CD_PROP1`	varchar(100)	NULL	DEFAULT NULL	COMMENT '코드속성1',
	`CD_PROP2`	varchar(100)	NULL	DEFAULT NULL	COMMENT '코드속성2',
	`CD_PROP3`	varchar(100)	NULL	DEFAULT NULL	COMMENT '코드속성3',
	`USE_YN`	char(1)	NOT NULL	DEFAULT 'Y'	COMMENT '사용여부',
	`RGDT`	datetime	NOT NULL	DEFAULT current_timestamp()	COMMENT '시작일시',
	`UPDT`	datetime	NOT NULL	DEFAULT current_timestamp() on update current_timestamp()	COMMENT '수정일시'
) COMMENT '코드';


CREATE TABLE `TB_AF_DAG` (
	`DAG_ID`	varchar(250)	NOT NULL  PRIMARY KEY  COMMENT 'DAG ID',
	`DAG_DESC`	varchar(200)	NOT NULL	COMMENT 'DAG 설명',
	`DAG_FILE_PATH`	varchar(500)	NOT NULL	COMMENT 'DAG 파일경로',
	`USE_YN`	char(1)	NOT NULL	DEFAULT 'Y'	COMMENT '사용여부',
	`RGDT`	datetime	NOT NULL	DEFAULT current_timestamp()	COMMENT '시작일시',
	`UPDT`	datetime	NOT NULL	DEFAULT current_timestamp() on update current_timestamp()	COMMENT '수정일시'
) COMMENT 'airflow DAG';


CREATE TABLE `TB_AF_RUN` (
	`RUN_ID`	varchar(100)	NOT NULL  PRIMARY KEY  COMMENT 'RUN ID',
	`DAG_ID`	varchar(250)	NOT NULL	COMMENT 'DAG ID',
	`START_DATE`	datetime	NULL,
	`END_DATE`	datetime	NULL,
	`STATUS`	char(1)	NOT NULL	DEFAULT 'W'	COMMENT '사용여부',
	`RGDT`	datetime	NOT NULL	DEFAULT current_timestamp()	COMMENT '시작일시',
	`UPDT`	datetime	NOT NULL	DEFAULT current_timestamp() on update current_timestamp()	COMMENT '수정일시'
) COMMENT 'airflow 실행 인스턴스';


CREATE TABLE `TB_AF_TARGET` (
  `RUN_ID` varchar(100) NOT NULL  PRIMARY KEY  COMMENT 'RUN ID',
  `TARGET_ID` varchar(36) NOT NULL  PRIMARY KEY  COMMENT 'TARGET ID',
  `CONTENT` longtext NOT NULL COMMENT 'TARGET JSON',
  `USE_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  `RGDT` datetime NOT NULL DEFAULT current_timestamp() COMMENT '시작일시',
  `UPDT` datetime NOT NULL DEFAULT current_timestamp() on update current_timestamp() COMMENT '수정일시'
) COMMENT 'airflow 작업대상';


CREATE TABLE `TB_AF_COMPLETE` (
    `COMPLETE_ID` INT AUTO_INCREMENT NOT NULL COMMENT '완료작업ID',
    `RUN_ID` VARCHAR(100) NOT NULL COMMENT '실행인스턴스ID',
    `CONTENT` LONGTEXT NOT NULL COMMENT '작업내용',
    `USE_YN` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
    `RGDT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '시작일시',
    `UPDT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CONSTRAINT `CHK_JSON_CONTENT` CHECK (JSON_VALID(`CONTENT`)),
    CONSTRAINT `PK_TB_AF_COMPLETE` PRIMARY KEY (`COMPLETE_ID`)
) COMMENT='완료작업 정보';


CREATE TABLE `TB_AF_COMPLETE_MAP` (
    `COMPLETE_ID` INT NULL COMMENT '완료작업ID',
    `TABLE_ID` INT NULL COMMENT '테이블ID',
    `PK_VALUE` INT NULL COMMENT '테이블 PK값',
    INDEX `IDX_TABLE_PK` (`TABLE_ID`, `PK_VALUE`) -- 조회 최적화를 위한 인덱스
) COMMENT='완료작업 매핑';


CREATE TABLE `TB_DI_COMMON_CRCTN` (
	`COMMON_CRCTN_ID`	int	NOT NULL comment '공통 교정 ID', 
	`ERROR_TEXT`	varchar(50)	NULL COMMENT '에러 텍스트',
	`CRRCT_TEXT`	varchar(50)	NULL COMMENT '올바른 텍스트',
	`CRCTN_CNT`	int	NULL COMMENT '교정 횟수'
)COMMENT '공통 교정 사전' ;

ALTER TABLE `TB_DI_COMMON_CRCTN` ADD CONSTRAINT `PK_TB_DI_COMMON_CRCTN` PRIMARY KEY (
	`COMMON_CRCTN_ID`
);

ALTER TABLE TB_DI_COMMON_CRCTN MODIFY COLUMN COMMON_CRCTN_ID INT NOT NULL AUTO_INCREMENT COMMENT '공통 교정 ID';

CREATE TABLE `TB_DI_BLOCK_CLASS` (
	`BLOCK_CLASS_ID`	int	NOT NULL COMMENT '블록 클래스 ID',
	`SECTION_CLASS_ID`	int	NOT NULL COMMENT '영역 클래스 ID',
	`BLOCK_ROW_NUM`	int	NULL	DEFAULT 0 COMMENT '블록 행 값',
	`BLOCK_COL_NUM`	int	NULL	DEFAULT 0 COMMENT '블록 열 값',
	`BLOCK_TYPE`	varchar(50)	NULL  COMMENT '블록 구분',
	`PARENT_BLOCK_ID`	int	NULL  COMMENT '부모 블록 ID',
	`DEFAULT_TEXT`	varchar(200)	NULL  COMMENT '기본값 텍스트'
)COMMENT 'ocr 데이터 검수 테이블' ;

ALTER TABLE `TB_DI_BLOCK_CLASS` ADD CONSTRAINT `PK_TB_DI_BLOCK_CLASS` PRIMARY KEY (
	`BLOCK_CLASS_ID`
);
ALTER TABLE TB_DI_BLOCK_CLASS MODIFY COLUMN BLOCK_CLASS_ID INT NOT NULL AUTO_INCREMENT COMMENT '블록 클래스 ID';


CREATE TABLE `TB_DI_BLOCK_CRCTN` (
	`BLOCK_CRCTN_ID`	int	NOT NULL COMMENT '블록 교정 ID',
	`BLOCK_CLASS_ID`	int	NOT NULL COMMENT '블록 클래스 ID',
	`ERROR_TEXT`	varchar(50)	NULL  COMMENT '에러 텍스트',
	`CRRCT_TEXT`	varchar(50)	NULL COMMENT '올바른 텍스트',
	`CRCTN_CNT`	int	NULL  COMMENT '교정 횟수'
)COMMENT '공통 교정 사전';


ALTER TABLE `TB_DI_BLOCK_CRCTN` ADD CONSTRAINT `PK_TB_DI_BLOCK_CRCTN` PRIMARY KEY (
	`BLOCK_CRCTN_ID`
);

ALTER TABLE TB_DI_BLOCK_CRCTN MODIFY COLUMN BLOCK_CRCTN_ID INT NOT NULL AUTO_INCREMENT COMMENT '블록 교정 ID';



CREATE TABLE `TB_DI_DOC_CLASS` (
	`DOC_CLASS_ID`	int	NOT NULL COMMENT '문서 클래스 ID',
	`DOC_CLASS_NAME`	varchar(100)	NULL COMMENT '문서 클래스 명',
	`RGDT`	datetime	NULL	DEFAULT current_timestamp(),
	`UPDT`	datetime	NULL	DEFAULT current_timestamp() on update current_timestamp()
)COMMENT '문서 분류 테이블';

ALTER TABLE `TB_DI_DOC_CLASS` ADD CONSTRAINT `PK_TB_DI_DOC_CLASS` PRIMARY KEY (
	`DOC_CLASS_ID`
);

ALTER TABLE TB_DI_DOC_CLASS MODIFY COLUMN DOC_CLASS_ID INT NOT NULL AUTO_INCREMENT COMMENT '문서 클래스 ID';



CREATE TABLE `TB_DI_LAYOUT_CLASS` (
	`LAYOUT_CLASS_ID`	int	NOT NULL COMMENT '레이아웃 클래스 ID',
	`DOC_CLASS_ID`	int	NOT NULL COMMENT '문서 클래스 ID' ,
	`LAYOUT_CLASS_NAME`	varchar(100)	NULL COMMENT '레이아웃 클래스명',
	`LAYOUT_CLASS_DESC`	varchar(200)	NULL COMMENT ' ',
	`LAYOUT_ORDER`	int	NULL	DEFAULT 0 COMMENT '레이아웃 순서',
	`IMG_PREPROCESS_INFO`	longtext	NULL COMMENT '이미지 전처리 정보' ,
	`CLASSIFY_AI_INFO`	longtext	NULL COMMENT '분류 ai 정보',
	`RGDT`	datetime	NULL	DEFAULT current_timestamp(),
	`UPDT`	datetime	NULL	DEFAULT current_timestamp() on update current_timestamp()
)COMMENT '이미지 분류, 전처리 설정파일 테이블';

ALTER TABLE `TB_DI_LAYOUT_CLASS` ADD CONSTRAINT `PK_TB_DI_LAYOUT_CLASS` PRIMARY KEY (
	`LAYOUT_CLASS_ID`
);


ALTER TABLE TB_DI_LAYOUT_CLASS MODIFY COLUMN  LAYOUT_CLASS_ID INT NOT NULL AUTO_INCREMENT COMMENT '레이아웃 클래스 ID';


CREATE TABLE `TB_DI_SECTION_CLASS` (
	`SECTION_CLASS_ID`	int	NOT NULL COMMENT '구역 클래스 ID',
	`LAYOUT_CLASS_ID`	int	NOT NULL COMMENT '레이아웃 클래스 ID',
	`SECTION_NAME`	varchar(100)	NULL  COMMENT '구역 명',
	`SECTION_DESC`	varchar(200)	NULL,
	`SECTION_ORDER`	int	NULL	DEFAULT 0,
	`SEPARATE_AREA_INFO`	longtext	NULL COMMENT '영역분리 정보',
	`SEPARATE_BLOCK_INFO`	longtext	NULL COMMENT '영역블록 정보',
	`OCR_INFO`	longtext	NULL  COMMENT 'OCR 정보',
	`CLEANSING_INFO`	longtext	NULL COMMENT '정제 정보',
	`RGDT`	datetime	NULL	DEFAULT current_timestamp(),
	`UPDT`	datetime	NULL	DEFAULT current_timestamp() on update current_timestamp()
)COMMENT '영역분리, OCR 설정파일 테이블';

ALTER TABLE `TB_DI_SECTION_CLASS` ADD CONSTRAINT `PK_TB_DI_SECTION_CLASS` PRIMARY KEY (
	`SECTION_CLASS_ID`
);

ALTER TABLE TB_DI_SECTION_CLASS MODIFY COLUMN SECTION_CLASS_ID INT NOT NULL AUTO_INCREMENT COMMENT '구역 클래스 ID';











CREATE TABLE `TB_DS_TABLE` (
  `TABLE_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '테이블ID',
  `TABLE_NM` varchar(100) NOT NULL COMMENT '테이블명',
  `TABLE_DESC` varchar(200) DEFAULT NULL COMMENT '테이블 설명',
  `PARENT_TABLE_ID` int(11) DEFAULT NULL COMMENT '부모 테이블ID',
  PRIMARY KEY (`TABLE_ID`)
) COMMENT='데이터 테이블';

CREATE TABLE `TB_DS_COLUMN` (
    `COLUMN_ID`      INT AUTO_INCREMENT PRIMARY KEY COMMENT '컬럼ID',
    `TABLE_ID`       INT NOT NULL COMMENT '테이블ID',
    `COLUMN_NM`    VARCHAR(100) NOT NULL COMMENT '컬럼명',
    `DATA_TYPE`      VARCHAR(50) NOT NULL COMMENT '데이터 타입',
    `IS_NULLABLE`    CHAR(1) NOT NULL DEFAULT 'Y' COMMENT 'NULL 허용 여부',
    `IS_PK`          CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'PK 여부',
    `COLUMN_DESC`    VARCHAR(200) COMMENT '컬럼 설명',
    `COLUMN_ORDER`   INT COMMENT '컬럼 순서',	
    `INPUT_FORMAT`   VARCHAR(100) COMMENT '입력 포맷'
) COMMENT='데이터 테이블 컬럼';





CREATE TABLE `TB_OCR_FLR_STATUS` (
	`FLR_SEQ_NUM`	INT	NULL COMMENT '건축물 현황 시퀀스 번호',
	`BILD_SEQ_NUM`	VARCHAR(255)	NOT NULL COMMENT '건물 시퀀스 번호',
	`FLR_CLASS_TYPE`	VARCHAR(20)	NULL COMMENT '층 구분 유형 (예: 주1, 지1)',
	`FLR_NUM_TEXT`	VARCHAR(20)	NULL COMMENT '층 번호 (예: 1, 지하1층)',
	`FLR_STRUCT_TYPE`	VARCHAR(100)	NULL COMMENT '층 구조 유형',
	`FLR_PURP_TYPE`	VARCHAR(100)	NULL COMMENT '층 용도 유형',
	`FLR_AREA_SQM`	VARCHAR(100)	NULL COMMENT '층 면적 (제곱미터)'
)COMMENT='건축물 현황 정보 테이블';

ALTER TABLE `TB_OCR_FLR_STATUS` ADD CONSTRAINT `PK_TB_OCR_FLR_STATUS` PRIMARY KEY (
	`FLR_SEQ_NUM`
);

ALTER TABLE TB_OCR_FLR_STATUS MODIFY COLUMN FLR_SEQ_NUM INT NOT NULL AUTO_INCREMENT COMMENT '건축물 현황 시퀀스 번호';

CREATE TABLE `TB_OCR_BILD_BASIC_INFO` (
	`BILD_SEQ_NUM`	INT	NOT NULL COMMENT '건물 시퀀스 번호',
	`BILD_ID`	VARCHAR(50)	NULL	COMMENT '건축물 고유 식별자',
	`UNIQUE_NUM`	VARCHAR(50)	NULL	COMMENT '건축물 고유번호',
	`BILD_NAME`	VARCHAR(100)	NULL	COMMENT '건축물 명칭',
	`UNIT_HOUSEHOLD_POP`	VARCHAR(50)	NULL	COMMENT '호수/가구수/세대수',
	`LAND_LOC_ADDR`	VARCHAR(255)	NULL	COMMENT '대지위치 주소',
	`LAND_LOT_NUM`	VARCHAR(50)	NULL	COMMENT '지번',
	`ROAD_NM_ADDR`	VARCHAR(255)	NULL	COMMENT '도로명주소',
	`LAND_AREA_SQM`	VARCHAR(100)	NULL	COMMENT '대지 면적 (제곱미터)',
	`TOT_FLR_AREA_SQM`	VARCHAR(100)	NULL	COMMENT '연면적 (제곱미터)',
	`ADMIN_DIST_NM`	VARCHAR(50)	NULL	COMMENT '지역명',
	`SECT_TYPE`	VARCHAR(50)	NULL	COMMENT '지구 유형',
	`ZONE_TYPE`	VARCHAR(50)	NULL	COMMENT '구역 유형',
	`BILD_AREA_SQM`	VARCHAR(100)	NULL	COMMENT '건축 면적 (제곱미터)',
	`FAR_CALC_AREA_SQM`	VARCHAR(100)	NULL	COMMENT '용적률 산정 연면적 (제곱미터)',
	`MAIN_STRUCT_TYPE`	VARCHAR(100)	NULL	COMMENT '주구조 유형',
	`MAIN_PURPOSE_TYPE`	VARCHAR(100)	NULL	COMMENT '주용도 유형',
	`TOT_FLR_CNT`	VARCHAR(50)	NULL	COMMENT '총 층수',
	`BILD_COVERAGE_RATIO`	VARCHAR(100)	NULL	COMMENT '건폐율 (%)',
	`FLR_AREA_RATIO`	VARCHAR(100)	NULL	COMMENT '용적률 (%)',
	`BILD_HEIGHT_METER`	VARCHAR(100)	NULL	COMMENT '건축물 높이 (미터)',
	`ROOF_STRUCT_TYPE`	VARCHAR(100)	NULL	COMMENT '지붕 구조 유형',
	`ANNEX_BILD_TYPE`	VARCHAR(50)	NULL	COMMENT '부속 건축물 유형',
	`LNDSCP_AREA_SQM`	VARCHAR(100)	NULL	COMMENT '조경 면적 (제곱미터)',
	`PUB_OPEN_AREA_SQM`	VARCHAR(100)	NULL	COMMENT '공개 공지 면적 (제곱미터)',
	`SETBACK_AREA_SQM`	VARCHAR(100)	NULL	COMMENT '건축선 후퇴 면적 (제곱미터)',
	`SETBACK_DIST_METER`	VARCHAR(100)	NULL	COMMENT '건축선 후퇴 거리 (미터)'
)COMMENT='일반건축물대장 정보 테이블';


ALTER TABLE `TB_OCR_BILD_BASIC_INFO` ADD CONSTRAINT `PK_TB_OCR_BILD_BASIC_INFO` PRIMARY KEY (
	`BILD_SEQ_NUM`
);
ALTER TABLE TB_OCR_BILD_BASIC_INFO MODIFY COLUMN BILD_SEQ_NUM INT NOT NULL AUTO_INCREMENT COMMENT '건물 시퀀스 번호';


CREATE TABLE `TB_OCR_OWN_STATUS` (
	`OWNR_SEQ_NUM`	INT	NULL  COMMENT '소유자 현황 시퀀스 번호',
	`BILD_SEQ_NUM`	VARCHAR(255)	NOT NULL COMMENT '건물 시퀀스 번호',
	`OWNR_FULL_NM`	VARCHAR(100)	NULL COMMENT '소유자 성명 또는 명칭',
	`OWNR_ID_REG_NUM`	VARCHAR(50)	NULL COMMENT '주민/법인 등록번호',
	`OWNR_ADDR_FULL`	VARCHAR(255)	NULL COMMENT '소유자 전체 주소',
	`OWNR_SHARE_RATIO`	VARCHAR(20)	NULL COMMENT '소유권 지분 비율',
	`OWNR_CHG_DATE`	VARCHAR(100)	NULL COMMENT '소유권 변동일',
	`ADDR_CHG_CATEGORY`	VARCHAR(100)	NULL COMMENT '주소 변동 구분'
)COMMENT='소유자 현황 정보 테이블';

ALTER TABLE `TB_OCR_OWN_STATUS` ADD CONSTRAINT `PK_TB_OCR_OWN_STATUS` PRIMARY KEY (
	`OWNR_SEQ_NUM`
);

ALTER TABLE TB_OCR_OWN_STATUS MODIFY COLUMN OWNR_SEQ_NUM INT NOT NULL AUTO_INCREMENT COMMENT '소유자 현황 시퀀스 번호';

